// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2yNCWBiMxrwJ8UTY2OieVV3GLMsmM6Kw',
    appId: '1:1035356635294:web:1f6ffee5c93143880ffb8f',
    messagingSenderId: '1035356635294',
    projectId: 'vintage-c55d3',
    authDomain: 'vintage-c55d3.firebaseapp.com',
    storageBucket: 'vintage-c55d3.firebasestorage.app',
    measurementId: 'G-8GWVJDVWK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdeimku5qHDpNf6nC-P3GeBzas2pgaQ9A',
    appId: '1:1035356635294:android:f9cbd74f973934400ffb8f',
    messagingSenderId: '1035356635294',
    projectId: 'vintage-c55d3',
    storageBucket: 'vintage-c55d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9q_6AcsvOOjfLZRbzZpLdwCwmhtrfT4c',
    appId: '1:1035356635294:ios:889f5081ab6004140ffb8f',
    messagingSenderId: '1035356635294',
    projectId: 'vintage-c55d3',
    storageBucket: 'vintage-c55d3.firebasestorage.app',
    iosBundleId: 'com.victorartonomy.vintage',
  );

}